language: python

python:
  - "2.6"
  - "2.7"

addons:
  apt:
    packages:
    - python-dev
    - libxml2-dev
    - libxslt1-dev

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: python -m pytest -v --durations=10 --cov="routing_neighbors"
